version: "3.8"

services:
  highlight-full-stack:
    build: .
    container_name: highlight-full-stack
    restart: unless-stopped
    privileged: true
    environment:
      # Override environment variables with Dockerfile values after start-infra runs
      - "ADMIN_PASSWORD=admin123"
      - "IN_DOCKER=true"
      - "IN_DOCKER_GO=true"
      - "ON_PREM=true"
      - "SSL=false"
      - "REACT_APP_AUTH_MODE=password"
      - "AUTH_MODE=password"
      - "ENVIRONMENT=hobby"
      - "DEMO_PROJECT_ID=1"
      - "DEFAULT_PROJECT_ID=1"
      - "DEFAULT_WORKSPACE_ID=1"
      - "SEED_ADMIN_EMAIL=admin@highlight.io"
      - "SEED_ADMIN_PASSWORD=admin123"
      - "BACKEND_IMAGE_NAME=ghcr.io/highlight/highlight-backend:docker-v0.5.5"
      - "FRONTEND_IMAGE_NAME=ghcr.io/highlight/highlight-frontend:docker-v0.5.5"
      - "OTLP_DOGFOOD_ENDPOINT=http://localhost:4318"
      - "OTLP_ENDPOINT=http://localhost:4318"
    ports:
      - "3000:3000"  # Frontend
      - "8082:8082"  # Backend
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - highlight-data:/highlight-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000", "&&", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

volumes:
  highlight-data: